"""add table disassembly

Revision ID: c6ffb8f43c40
Revises: 9d9013b471f0
Create Date: 2025-05-15 14:21:24.841701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ffb8f43c40'
down_revision: Union[str, None] = '9d9013b471f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disassemblies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_time', sa.Integer(), nullable=False),
    sa.Column('batteryPack_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batteryPack_id'], ['batteryPack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('timers', sa.Column('disassembly_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'timers', 'disassemblies', ['disassembly_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timers', type_='foreignkey')
    op.drop_column('timers', 'disassembly_id')
    op.drop_table('disassemblies')
    # ### end Alembic commands ###
